default:
  image: 911734752298.dkr.ecr.us-east-1.amazonaws.com/m5gnn_ci:v2.2

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pytest:
  stage: test
  tags:
    - gpu
  script:
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install pytest
    - python3 -m pytest ./tests/unit-tests

lint:
  stage: test
  tags:
    - gpu
  script:
    - python3 -m pip install --upgrade prospector pip
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - pylint --rcfile=./tests/lint/pylintrc ./python/graphstorm

e2e:
  stage: test
  tags:
    - gpu
  script:
    - python3 -m pip install --upgrade prospector pip
