---
version: 1.0
lm_model:
  bert_models: # bert model(s) definition, one bert model for each node type having text data
    -
      node_type: node
      model_name: "allenai/scibert_scivocab_uncased"
      gradient_checkpoint: True
gsf:
  basic:
    model_encoder_type: lm
    graph_name: ogbn-arxiv
    backend: nccl
    num_gpus: 4
    ip_config: ip_list.txt
    part_config: ogb_arxiv_nc_train_val_1p_4t/ogbn-arxiv.json
    verbose: true
    use_bert_cache: false
    refresh_cache: false
    gnn_warmup_epochs: 0
    mixed_precision: false
    no_validation: true
    mp_opt_level: O2
    train_nodes: -1
    debug: false
  gnn:
    fanout: "4"
    n_layers: 1
    n_hidden: 128
    mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: ./models/ogb_arxiv/bert-tune/
    save_embeds_path: null
  hyperparam:
    dropout: 0.
    lr: 0.001
    bert_tune_lr: 0.0001
    n_epochs: 10
    batch_size: 4
    eval_batch_size: 32
    bert_infer_bs: 64
    wd_l2norm: 0
  mlm:
    mlm_probability: "0.15"

